"""
Django settings for raffles_site project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_d5c+!6=hp)i$nh#ny8+_omvumpe)k20@_ez9vnk4xp0ud1i7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
   "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #mis apps
    'raffles_app',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'raffles_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'raffles_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",   # carpeta para tus archivos estáticos del proyecto
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # para producción (collectstatic)

# Archivos de medios (uploads de usuarios, imágenes de motos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


LOGIN_URL = "login"            # si no está logueado, lo manda aquí
LOGIN_REDIRECT_URL = "home"    # después de login va aquí
LOGOUT_REDIRECT_URL = "home"   # después de logout va aquí



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "carlosforero2025777@gmail.com"
EMAIL_HOST_PASSWORD = "iozo bdoo gugr fff d"  # Usa contraseña de aplicación, no la normal
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# Habilita el soporte de zonas horarias
USE_TZ = True

# Configura la zona horaria a Colombia
TIME_ZONE = 'America/Bogota'



CRONJOBS = [
    ('*/10 * * * *', 'django.core.management.call_command', ['close_raffles']),
]

# pagos

# Wompi
WOMPI_PUBLIC_KEY = "pub_test_KGAaw9rhVA3qwVhmZZNzWPVYjgRYOOUx"
WOMPI_PRIVATE_KEY = "prv_test_wFisBFHGu1zksKJfxeL4yozBgENpcS5A"
WOMPI_EVENTS_SECRET = "test_events_3wbcKjBhc3OBqsB19ItbndJGathPDgUY"
WOMPI_INTEGRITY_SECRET = "test_integrity_oZGoUHob1gD0AFhhDDzuu5EOxXObIVuj"

WOMPI_BASE_URL = "https://sandbox.wompi.co/v1"  # 👈 solo hasta /v1
