# Generated by Django 5.2.6 on 2025-09-24 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_new', models.BooleanField(default=True)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Kilometraje en kilómetros (solo si es usada).', null=True)),
                ('condition', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular')], help_text='Condición general de la moto si es usada.', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motos/')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='raffles_app.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_tickets', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('finished', 'Finalizada con ganador')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ends_at', models.DateTimeField()),
                ('seed_commitment', models.CharField(blank=True, max_length=128, null=True)),
                ('seed_reveal', models.CharField(blank=True, max_length=256, null=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='raffles_app.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles_app.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('raffle', 'number')},
            },
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to='raffles_app.ticket'),
        ),
    ]
