# Generated by Django 5.2.6 on 2025-09-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional del slide', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo o descripción', max_length=200)),
                ('image', models.ImageField(help_text='Imagen principal del slide', upload_to='carousel/')),
                ('link', models.URLField(blank=True, help_text='Link opcional al que redirige el slide')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar este slide en el carrusel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
