# Generated by Django 5.2.6 on 2025-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0002_carouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
