# Generated by Django 5.2.6 on 2025-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0003_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
