# Generated by Django 5.2.6 on 2025-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0004_alter_profile_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
