# Generated by Django 5.2.6 on 2025-10-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0005_ticket_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycleimage',
            name='is_hologram',
            field=models.BooleanField(default=False, help_text='Marcar si esta imagen será usada en el card holográfico.'),
        ),
    ]
