# Generated by Django 5.2.6 on 2025-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0007_alter_raffle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Proxima'), ('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=20),
        ),
    ]
