# Generated by Django 5.2.6 on 2025-10-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0008_alter_raffle_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
