# Generated by Django 5.2.6 on 2025-10-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0009_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='condition',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Solo si es usada.', null=True),
        ),
        migrations.AlterField(
            model_name='motorcycleimage',
            name='is_hologram',
            field=models.BooleanField(default=False, help_text='Marca la imagen holográfica.'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Próxima'), ('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=20),
        ),
    ]
