# Generated by Django 5.2.6 on 2025-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0010_alter_carouselslide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(help_text='Imagen principal del slide', upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mostrar este slide en el carrusel'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='link',
            field=models.URLField(blank=True, help_text='Link opcional al que redirige el slide'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo o descripción', max_length=200),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(blank=True, help_text='Título opcional del slide', max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='condition',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular')], help_text='Condición general de la moto si es usada.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje en kilómetros (solo si es usada).', null=True),
        ),
        migrations.AlterField(
            model_name='motorcycleimage',
            name='is_hologram',
            field=models.BooleanField(default=False, help_text='Marcar si esta imagen será usada en el card holográfico.'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Proxima'), ('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=20),
        ),
    ]
