# Generated by Django 5.2.6 on 2025-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles_app', '0011_alter_carouselslide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='link',
            field=models.URLField(blank=True, help_text='Enlace opcional del slide'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Próxima'), ('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=20),
        ),
    ]
